# -*- coding: utf-8 -*-
"""movie_recommender

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdIbuUZ_eefco96-u3qzB7fvIJN2hezD
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()



import numpy as np

df1 = pd.read_csv('tmdb_5000_movies.csv')



df1.head()



df1

C = df1['vote_average'].mean
C

m = df1['vote_count'].quantile(0.9)
m

q_movies = df1.copy().loc[df1['vote_count'] >= m]
q_movies

def weighted_rating(x, m=m, C=C):
    v= x['vote_count']
    R= x['vote_average']
    return (v/ v+m) + (m/ m+v)

q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

q_movies = q_movies.sort_values('score', ascending=False)

q_movies[['title', 'vote_count', 'vote_average', 'score']].head(20)

pop = df1.sort_values('popularity', ascending=False)

import matplotlib.pyplot as plt

plt.figure(figsize=(18, 8))
plt.barh(pop['title'].head(10), pop['popularity'].head(10), align='center',
         color='teal')
plt.gca().invert_yaxis()
plt.xlabel('Popularity')
plt.title('Popular Movies')

df1['overview'].head()

from sklearn.feature_extraction.text import TfidfVectorizer

tdif = TfidfVectorizer(stop_words='english')

df1 ['overview'] = df1['overview'].fillna('')

tdif_matrix = tdif.fit_transform(df1['overview'])

tdif_matrix.shape

from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tdif_matrix, tdif_matrix)

indices = pd.Series(df1.index, index=df1['title']).drop_duplicates()

def get_recommendations(title, cosine_sim=cosine_sim):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda X: X[1], reverse=True)
  sim_scores = sim_scores[1:11]
  movie_indices = [i[0] for i in sim_scores]
  return df1['title'].iloc[movie_indices]

get_recommendations('Scarface')

get_recommendations('Platoon')

get_recommendations('Desperado')

get_recommendations('Running Scared')

get_recommendations('Black Hawk Down')

get_recommendations('Ice Age')

get_recommendations('Kung Fu Panda 2')

get_recommendations('Crocodile Dundee')

get_recommendations('Australia')

get_recommendations('Instructions Not Included')

get_recommendations('Titanic')

get_recommendations('Horrible Bosses')

get_recommendations('Safe')